language:      node_js
node_js:
  - "stable"
before_script:
  - psql -c 'create database pro-pro-lite;' -U postgres
install:       npm install
cache:
  directories:
    - node_modules
script:
  - npm test
after_success:
- npm run coveralls